# # -*- coding: utf-8 -*-
# """Linear Reg.ipynb
# 
# Automatically generated by Colaboratory.
# 
# Original file is located at
#     https://colab.research.google.com/drive/1XJQPkPKet2rlfv5dCuO5BQ1_a4Fl1Tw3
# """

file <- 'Medical-Cost.csv'

df <- read.csv(file) #, stringsAsFactors = TRUE)
head(df)

dim(df)

str(df)

cat <- c('sex','smoker','region')
for (c in cat){
  print(paste0(c, ": ", unique(df[c])))
}

df$sex <- ifelse(df$sex == 'female', 1, 0)
df$smoker <- ifelse(df$smoker == 'yes', 1, 0)
head(df)

install.packages('caret')
library(caret)
dummy <- dummyVars("~.", data = df) # ~. = everything
dfnew <- data.frame(predict(dummy, newdata = df))
head(dfnew)

corr <- cor(dfnew)
corr[upper.tri(corr)] <- NA
corr

library(dplyr)
library(reshape2)
meltcorr <- melt(corr) %>% 
mutate (Var1 = factor(Var1, levels = rev(levels(.$Var1))), Var2 = factor(Var2))

meltcorr

ggplot(meltcorr, aes(Var1, Var2, fill = value, label = round(value, 2))) + 
ggtitle ("Correlation Heatmap") + 
geom_tile() + 
geom_text(size = 3) + 
coord_equal() +
theme(plot.title = element_text(size = 14, face = "bold"),
axis.text.x = element_text(angle = -90, hjust = 0)) + 
scale_x_discrete(name = "") + 
scale_y_discrete(name = "") +
scale_fill_gradient2(low = "darkred", mid = "white", high = "navy",
midpoint = 0, na.value = "white", name = "Correlation", limits = c(-1,1))

install.packages('psych')
library(psych)
pairs.panels(dfnew[c('age', 'bmi','children','charges')])

model <- lm(charges ~ ., data = dfnew)
summary(model)

#seems like regions is is not very correlated with charges
#drop 4 regions and model again
head(dfnew)
df_noregions <- dfnew[,-c(6:9)]
head(df_noregions)
model_noregions <- lm(charges ~ ., data = df_noregions)
summary(model_noregions)

#Test two models with F-statistics at 0.05
anova(model, model_noregions)

#F-test indicates that the regions did not give significant on the prediction
#for medical charges. Hence, regions can be removed.

#Smoker are strongly correlated to the charges. What if we remove smoker?
df_nosmokers <- df_noregions[,-c(5)]
model_nosmokers <- lm(charges ~ ., data = df_nosmokers)
summary(model_nosmokers)

anova(model_noregions, model_nosmokers)

#F-test indicates that smokers cannot be removed from the model
#and give significant on the prediction.

#How about BMI? Can it be removed?
df_noBMI <- df_noregions[,-c(3)]
model_noBMI <- lm(charges ~ ., data = df_noBMI)
summary(model_noBMI)

#F-test
anova(model_noregions, model_noBMI)
#F-test indicates that BMI gives significant prediction on medical charges.
#Hence, cannot removed BMI.
#The final model is charges ~ age + sex + bmi + children + smoker.